name: ci

on: [push]

jobs:
  build_r:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        # build client code
      - run: npm i -g yarn
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ./.yarn/cache
            ./.yarn/unplugged
          key: ${{ runner.os }}-yarn2-v4-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-v4
      - run: yarn install
      - run: yarn build
      - run: yarn clean:r
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            webshot
            textshaping
            devtools

      - name: Style / Format
        shell: Rscript {0}
        run: styler::style_pkg(dry="fail")

      - name: Lint
        shell: Rscript {0}
        run: |
          devtools::document()
          devtools::load_all()
          lintr::lint_package()

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        shell: Rscript {0}
        run: |
          devtools::document()
          devtools::check(args = c("--no-manual", "--as-cran"), error_on = "error", check_dir = "check")

      - name: Test
        shell: Rscript {0}
        run: devtools::test()

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-results
          path: check

      - name: Build Package
        run: yarn build:r
      - name: Prepare Docs
        run: |
          mkdir -p public/integrations/r
          cp ./upsetjs.tar.gz public/integrations/r/
      - name: Build Website
        run: yarn docs:r
      - name: Copy Docs
        run: |
          mv docs/* public/integrations/r/

      - name: Deploy Main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: upsetjs/actions-gh-pages@sgratzl
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: upsetjs/upsetjs.github.io
          publish_branch: main
          publish_dir: ./public
          enable_jekyll: true
          remove_path_spec: 'integrations/r/'

      - if: github.ref == 'refs/heads/develop'
        # move to next directory
        run: |
          mv public public2
          mkdir -p public
          mv public2 public/next

      - name: Deploy Develop
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        uses: upsetjs/actions-gh-pages@sgratzl
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: upsetjs/upsetjs.github.io
          publish_branch: main
          publish_dir: ./public
          enable_jekyll: true
          remove_path_spec: 'next/integrations/r/'

  build_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        # build client code
      - run: npm i -g yarn
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ./.yarn/cache
            ./.yarn/unplugged
          key: ${{ runner.os }}-yarn2-v4-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-v4
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      # - run: yarn test --ci --coverage --maxWorkers=2
